In [1]:
from genetic_utils import *

In [7]:
csv_file = '../dataverse_files/mnist_06_combined.csv'
data = pd.read_csv(csv_file)
last_column = data.iloc[:, -1].values
last_column = np.where(last_column == "o", 0, 1)
tlabels = last_column
data = np.array(data)
data = data[:,:-1]

In [8]:
data.shape

(7003, 784)

In [9]:
import numpy as np
import matplotlib.pyplot as plt

def k_means_clustering(data, k, max_iterations=100, tolerance=1e-4):
    # Initialize centroids randomly
    centroids = data[np.random.choice(len(data), k, replace=False)]
    
    for _ in range(max_iterations):
        # Assign each data point to the nearest centroid
        distances = np.array([np.sum((data - centroid) ** 2, axis=1) for centroid in centroids])
        labels = np.argmin(distances, axis=0)
        # Update centroids
        new_centroids = np.array([data[labels == i].mean(axis=0) for i in range(k)])
        
        # Check for convergence
        if np.linalg.norm(new_centroids - centroids) < tolerance:
            break
        
        centroids = new_centroids
    
    return labels, centroids




In [10]:
# Example usage:
if __name__ == "__main__":
    # Generate random data for testing
    np.random.seed(42)
#     data = np.random.rand(7003, 784)
    
    # Set the number of clusters (k)
    k = 2
    
    # Perform K-means clustering
    labels, centroids = k_means_clustering(data, k)
    
    # Print the results
    print("Cluster labels:", labels)
    print("Centroids shape:", centroids.shape)


Cluster labels: [1 1 1 ... 1 1 1]
Centroids shape: (2, 784)


In [13]:
from sklearn.metrics import confusion_matrix
import numpy as np
# sklearn.metrics.confusion_matrix(lables, 1-classes, labels=None, sample_weight=None, normalize=None)
true_labels = 1 - tlabels
predicted_labels = 1 - labels

cm = confusion_matrix(true_labels, predicted_labels)

# Normalize the confusion matrix to get percentages
cm_percentage = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

print("Confusion Matrix (Percentage):")
print(cm_percentage)

Confusion Matrix (Percentage):
[[0.52122266 0.47877734]
 [0.87       0.13      ]]


In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score

true_labels = 1 - tlabels
predicted_labels = 1 - labels

precision = precision_score(true_labels, predicted_labels)

# Calculate recall
recall = recall_score(true_labels, predicted_labels)

# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.0039180229053646775
Recall: 0.13
F1 Score: 0.007606787595084846


In [36]:
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.datasets import make_blobs

# Example data generation
# n_samples = 300
# data, _ = make_blobs(n_samples=n_samples, centers=3, n_features=2, random_state=42)

# Fit a Gaussian Mixture Model
gmm = GaussianMixture(n_components=2)
gmm.fit(data)

# Predict probabilities
probabilities = gmm.predict_proba(data)

# Determine the maximum probability for each point
max_probabilities = np.max(probabilities, axis=1)

# Set a threshold for outliers
threshold = 0.9999

# Classify points as inliers (1) and outliers (0)
labels = (max_probabilities > threshold).astype(int)

# Print results
print("Inliers count:", np.sum(labels))
# print("Outliers count:", n_samples - np.sum(labels))

true_labels = 1 - tlabels
predicted_labels = 1 - labels

precision = precision_score(true_labels, predicted_labels)

# Calculate recall
recall = recall_score(true_labels, predicted_labels)

# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Inliers count: 6995
Precision: 0.0
Recall: 0.0
F1 Score: 0.0


In [42]:
true_labels = 1 - tlabels
predicted_labels = 1- labels

precision = precision_score(true_labels, predicted_labels)

# Calculate recall
recall = recall_score(true_labels, predicted_labels)

# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.0
Recall: 0.0
F1 Score: 0.0


In [35]:
max_probabilities.min()

0.9944614317768027

In [39]:
true_labels

array([0, 0, 0, ..., 1, 1, 1])

In [41]:
labels

array([1, 1, 1, ..., 1, 1, 1])

In [43]:
from sklearn.metrics import confusion_matrix
import numpy as np
# sklearn.metrics.confusion_matrix(lables, 1-classes, labels=None, sample_weight=None, normalize=None)
true_labels = 1 - tlabels
predicted_labels = 1 - labels

cm = confusion_matrix(true_labels, predicted_labels)

# Normalize the confusion matrix to get percentages
cm_percentage = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

print("Confusion Matrix (Percentage):")
print(cm)

Confusion Matrix (Percentage):
[[6895    8]
 [ 100    0]]
