In [1]:
from genetic_utils import *

In [2]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [28]:
csv_file = '../dataverse_files/mnist_06_combined.csv'
data = pd.read_csv(csv_file)
last_column = data.iloc[:, -1].values
last_column = np.where(last_column == "o", 0, 1)
labels = last_column
data = np.array(data)
data_n = data[:,:-1]

In [29]:
num_dims = data_n.shape[1]

In [23]:
data_n[1,:]

array([  42, -191, -142,  -65, -117,   55,   49, -170,  -45,    5, -325,
       -115, -107, -281, -257, -303,   54, -154, -101,  -47,  -31,  -28,
          1,  191,   72,  -38,   50,  -64,  -63,   98, -117, -113,  -46,
          2, -135,   25, -159,    1, -143,   38, -169,  -85,  -31, -323,
       -234, -334,  -88,  -73, -109,   -4,  -75,  -31,  -14, -137,  105,
        -94,   90, -132,    3,    7, -101, -195,   26,  109, -130,   48,
       -165,  -80, -133,  -50, -153, -148, -297, -194,  -96, -181,   -5,
       -289, -107, -179,  -21,    4,  -34,  115,   15,   15,  -74, -164,
        -73,  131, -202,  -15, -115, -308,   26,  -50,  -33,   25, -154,
         75, -191,   26, -227, -309, -284, -266, -163, -122, -185, -234,
       -212,    0,   -3,   -3,   22,  -12,  156,   36,   82,   31,   82,
         70,  111, -110, -133,  -13,  -26,   75, -107, -187,   13, -138,
        -77, -129, -224,  -89,   51,  -70,  -19,  -35,  -29,    3,   43,
         10, -178, -102, -119,  -57,  -70,   53,  -

In [18]:
np.sqrt(4222)

64.97691897897283

In [24]:
model, history = train_VAE(data_n, num_dims=num_dims, latent_dim=256,kl_loss_factor = 0.001, hidden_layer_n=[256, 128, 64],epochs = 100, batch_size = 8 )

In [25]:
history.history["reconstruction_loss"]

[11933.4365234375,
 10308.7041015625,
 9257.2099609375,
 8457.6640625,
 7907.20947265625,
 7507.2646484375,
 7194.1533203125,
 6977.7412109375,
 6777.94482421875,
 6644.67724609375,
 6531.2734375,
 6451.53759765625,
 6403.8359375,
 6329.931640625,
 6269.61865234375,
 6208.91259765625,
 6175.65673828125,
 6104.41259765625,
 6056.72021484375,
 6012.3291015625,
 5971.8857421875,
 5933.78173828125,
 5903.54052734375,
 5857.55322265625,
 5824.8896484375,
 5840.56005859375,
 5847.32275390625,
 5819.2568359375,
 5735.634765625,
 5667.48388671875,
 5728.92822265625,
 5550.78857421875,
 5438.32568359375,
 5372.53125,
 5335.4755859375,
 5302.939453125,
 5253.61474609375,
 5168.1826171875,
 5101.82080078125,
 5054.14697265625,
 4992.037109375,
 4937.6259765625,
 4875.7734375,
 4826.9306640625,
 4811.71923828125,
 4763.7861328125,
 4726.54443359375,
 4686.6767578125,
 4675.22802734375,
 4638.490234375,
 4627.09423828125,
 4632.65625,
 4580.66162109375,
 4578.18017578125,
 4556.4423828125,
 4548.86

In [17]:
history.history["reconstruction_loss"]

[7408.37841796875,
 5995.4267578125,
 5203.39013671875,
 4747.6455078125,
 4493.34619140625,
 4356.11083984375,
 4285.36572265625,
 4252.86767578125,
 4235.39404296875,
 4228.11572265625,
 4225.28759765625,
 4222.96484375,
 4222.10888671875,
 4223.94921875,
 4221.62109375,
 4224.046875,
 4223.7626953125,
 4222.64892578125,
 4221.56689453125,
 4222.9501953125,
 4225.30859375,
 4220.72802734375,
 4220.9912109375,
 4223.39306640625,
 4223.38232421875,
 4219.10791015625,
 4221.68994140625,
 4222.37255859375,
 4222.08642578125,
 4224.810546875,
 4223.30322265625,
 4224.32373046875,
 4220.76025390625,
 4223.08935546875,
 4222.74365234375,
 4221.16455078125,
 4222.03857421875,
 4224.23828125,
 4222.19482421875,
 4222.9853515625,
 4222.10009765625,
 4221.060546875,
 4224.708984375,
 4223.6279296875,
 4223.83935546875,
 4219.96142578125,
 4225.6552734375,
 4219.80126953125,
 4223.39306640625,
 4222.55419921875,
 4224.16259765625,
 4221.76904296875,
 4223.130859375,
 4220.6748046875,
 4223.42529

In [11]:
classes = vae_detect_outliers(data_n, model, num_dims, std_k=3)

In [13]:
true_labels = 1 - labels
predicted_labels = 1 - classes

precision = precision_score(true_labels, predicted_labels)

# Calculate recall
recall = recall_score(true_labels, predicted_labels)

# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.14492753623188406
Recall: 0.1
F1 Score: 0.1183431952662722


In [23]:
from sklearn.metrics import confusion_matrix
import numpy as np
# sklearn.metrics.confusion_matrix(lables, 1-classes, labels=None, sample_weight=None, normalize=None)
true_labels = 1- labels
predicted_labels = 1 - classes

cm = confusion_matrix(true_labels, predicted_labels)

# Normalize the confusion matrix to get percentages
cm_percentage = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

print("Confusion Matrix (Percentage):")
print(cm)

Confusion Matrix (Percentage):
[[6931   59]
 [  90   10]]


In [30]:
model2, history2 = train_RAE(data_n, num_dims=num_dims,z_loss_w = 0.001,REG_loss_w = 0.001, latent_dim=128, hidden_layer_n=[512, 256, 128], batch_size = 8 )

In [31]:
history2.history["reconstruction_loss"]

[4879.66943359375,
 4167.28271484375,
 4167.828125,
 4168.07275390625,
 4168.25,
 4167.69775390625,
 4167.66796875,
 4168.6826171875,
 4167.94482421875,
 4167.9169921875,
 4168.03076171875,
 4168.03076171875,
 4168.21484375,
 4168.12744140625,
 4168.05078125,
 4168.03369140625,
 4167.84619140625,
 4167.8671875,
 4167.80712890625,
 4167.6064453125,
 4168.0537109375,
 4167.2734375,
 4167.45849609375,
 4167.49951171875,
 4168.3603515625,
 4168.02587890625,
 4168.146484375,
 4167.69921875,
 4168.23486328125,
 4167.89013671875,
 4167.38232421875,
 4168.49560546875,
 4168.3310546875,
 4168.2802734375,
 4167.41845703125,
 4167.87255859375,
 4167.5546875,
 4168.4208984375,
 4167.8935546875,
 4168.0537109375,
 4167.994140625,
 4168.30517578125,
 4168.3017578125,
 4168.34814453125,
 4168.12744140625,
 4167.6357421875,
 4167.712890625,
 4168.4912109375,
 4167.7568359375,
 4168.08203125,
 4168.48486328125,
 4168.3291015625,
 4168.18017578125,
 4168.00390625,
 4168.02197265625,
 4167.767578125,
 41

In [20]:
classes2 = rae_detect_outliers(data_n, model2, num_dims, std_k=3)

In [21]:
true_labels = 1 - labels
predicted_labels = 1 - classes2

precision = precision_score(true_labels, predicted_labels)

# Calculate recall
recall = recall_score(true_labels, predicted_labels)

# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.14492753623188406
Recall: 0.1
F1 Score: 0.1183431952662722


In [22]:
from sklearn.metrics import confusion_matrix
import numpy as np
# sklearn.metrics.confusion_matrix(lables, 1-classes, labels=None, sample_weight=None, normalize=None)
true_labels = 1- labels
predicted_labels = 1 - classes2

cm = confusion_matrix(true_labels, predicted_labels)

# Normalize the confusion matrix to get percentages
cm_percentage = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

print("Confusion Matrix (Percentage):")
print(cm)

Confusion Matrix (Percentage):
[[6931   59]
 [  90   10]]
